name: Test - Upload Multiple Artifacts
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-action:
    strategy:
      matrix:
        config:
          - artifacts.test.json
          - artifacts.test-wc.json
          - artifacts.test-empty.json
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v4
      - name: Build action
        run: |
          npm install
          npm run build
      - name: Upload Multiple Artifacts
        uses: ./. 
        with:
          config: tests/${{ matrix.config }}
          continue-on-error: 'false'
      - name: Download artifacts using gh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          rm -rf downloaded
          mkdir -p downloaded
          jq -r '.[].name // empty' ${{matrix.config}} | while IFS= read -r name; do
            echo "Downloading artifact: $name"
            gh run download ${{ github.run_id }} --name "$name" -D downloaded
          done
      - name: Compare logs artifact contents
        run: |
          diff -ru tests/fixtures/logs downloaded/logs
      - name: Compare reports artifact contents
        run: |
          mkdir -p expected_reports
          cp -r tests/fixtures/coverage expected_reports/
          mkdir -p expected_reports/reports
          cp tests/fixtures/reports/junit.xml expected_reports/reports/junit.xml
          diff -ru expected_reports downloaded/reports

  check-all-green:
    if: always()
    needs:
      - test-action
    runs-on: ubuntu-latest
    steps:
      - name: Check if the needed jobs succeeded or failed
        id: check-jobs
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
